#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  7 18:38:28 2020

@author: camillelin
"""


num=int(input("how many students?"))
scores=[]
for i in range(num):
    name=input('name?')
    score=(int(input('score?')))
    scores.append(name)
    scores.append(score)
    
def average(scores):
    
    total=0
    
    for i in range(1, 2*num, 2):
        
        total = total+scores[i]
        
        return (total//num)

print("班平均為",average(scores))
 


    
    
    

