#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 29 20:44:50 2020

@author: camillelin
"""


scores=[]
names=[]
num=int(input("班上共有多少人?"))
for i in range(num):
    name=input("姓名？")
    names.append(name)
    score=int(input("score?"))
    scores.append(score)
    

high = 0
highname=' '
for i in range(num):
    if scores[i]>high:
        high=scores[i]
        highname= names[i]
    
low = 100
lowname=' '
for i in range(num):
    if scores[i]<low:
        low=scores[i]
        lowname= names[i]
    
print("average=",sum(scores)//int(num))

print(highname,"gets the highest score in",high)
print(lowname,"gets the lowest score in",low)
